version: '3.4'

services:
  crisescontrol.auth:
    image: ${DOCKER_REGISTRY-}crisescontrolauth
    build:
      context: .
      dockerfile: CrisesControl.Auth/Dockerfile
    ports:
    - "8080:80"
    - "8443:443"

  db:
    image: "mcr.microsoft.com/mssql/server"
    working_dir: /c/db
    environment:
        SA_PASSWORD: "P@ssword"
        ACCEPT_EULA: "Y"
    ports:
    - "4433:1433"
    volumes:
    - /c/db:/db
    - /c/dbenvironment/data:/var/opt/mssql/data
    - /c/dbenvironment/log:/var/opt/mssql/log

  crisescontrol.api:
    image: ${DOCKER_REGISTRY-}crisescontrolapi
    build:
      context: .
      dockerfile: CrisesControl/Dockerfile
    depends_on:
    - "db"
    ports:
    - "8081:80"
    - "8444:443"

volumes:
  db:
    driver: local
